services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "1234:3306"
    volumes:
      - mysql:/var/lib/mysql:rw
      # - ./entrypoint.sql:/docker-entrypoint-initdb.d/init.sql:rw
    container_name: fullcycle_desafio_db
    networks:
      - batata
  app:
    build: .
    ports:
      - "5555:3000"
    container_name: fullcycle_desafio_node_app
    depends_on:
      - db
    networks:
      - batata
    restart: on-failure:10
  web:
    build: ./nginx
    ports:
      - "8080:80"
    container_name: fullcycle_desafio_web_nginx
    depends_on:
      - app
    networks:
      - batata
    environment:
      - NGINX_PORT=80
volumes:
  mysql:
networks:
  batata:
    name: batata
