services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main
    ports:
      - "1234:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/initdb.sql
    container_name: fullcycle_desafio_db
    networks:
      - fullcycle_desafio_network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5
  app:
    image: node
    container_name: fullcycle_desafio_node_app
    depends_on:
      db:
        condition: "service_healthy"
    networks:
      - fullcycle_desafio_network
    restart: on-failure:10
    volumes:
      - ./app:/app
    working_dir: /app
    entrypoint: ["bash", "-c", "/app/init.sh"]
  web:
    build: ./nginx
    ports:
      - "8080:80"
    container_name: fullcycle_desafio_web_nginx
    depends_on:
      app:
        condition: "service_started"
    networks:
      - fullcycle_desafio_network
    environment:
      - NGINX_PORT=80
networks:
  fullcycle_desafio_network:
    name: fullcycle_desafio_network
