services:
  db:
    build: ./db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main
    ports:
      - "1234:3306"
    volumes:
      - ./mysql:/var/lib/mysql:rw
    container_name: fullcycle_desafio_db
    networks:
      - fullcycle_desafio_network
  app:
    image: node
    container_name: fullcycle_desafio_node_app
    depends_on:
      - db
    networks:
      - fullcycle_desafio_network
    restart: on-failure:10
    volumes:
      - ./app:/app
    working_dir: /app
    entrypoint: ["bash", "-c", "/app/init.sh"]
  web:
    build: ./nginx
    ports:
      - "8080:80"
    container_name: fullcycle_desafio_web_nginx
    depends_on:
      - app
    networks:
      - fullcycle_desafio_network
    environment:
      - NGINX_PORT=80
volumes:
  mysql:
  app:
networks:
  fullcycle_desafio_network:
    name: fullcycle_desafio_network
